[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd frontend && npm install && npm run build && cd .."

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10